// AFK Bot for Griefers SMP — generated by AFK Bot Manager
// Keeps your Aternos server alive 24/7 by staying connected.
// Requires Node.js + mineflayer:  npm install mineflayer

const mineflayer = require("mineflayer");

const config = {
  host: "GriefersSMP.aternos.me",
  port: 25565,
  username: "AFK_Bot",
    version: false, // auto-detect
  auth: "offline",
};

const RECONNECT_INTERVAL = 10000;
const ANTI_AFK = true;
const AUTO_RECONNECT = true;

let bot;
let antiAfkTimer;

function log(msg) {
  console.log(`[${new Date().toLocaleString()}] ${msg}`);
}

function createBot() {
  log("Connecting to " + config.host + ":" + config.port + " ...");
  bot = mineflayer.createBot(config);

  bot.once("spawn", () => {
    log("✅ Bot spawned — server kept alive");
    if (ANTI_AFK) {
      antiAfkTimer = setInterval(() => {
        if (bot && bot.entity) {
          bot.setControlState("jump", true);
          setTimeout(() => bot.setControlState("jump", false), 400);
        }
      }, 30000);
    }
  });

  bot.on("chat", (user, message) => {
    log("<" + user + "> " + message);
    if (message === "!quit" && user === config.username) bot.quit();
  });

  bot.on("kicked", (reason) => log("⚠️ Kicked: " + JSON.stringify(reason)));
  bot.on("error", (err) => log("❌ Error: " + err.message));
  bot.on("end", () => {
    log("Disconnected");
    if (antiAfkTimer) clearInterval(antiAfkTimer);
    if (AUTO_RECONNECT) {
      log("Reconnecting in " + RECONNECT_INTERVAL / 1000 + "s ...");
      setTimeout(createBot, RECONNECT_INTERVAL);
    }
  });
}

createBot();